kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: accelerator-clusterrole
rules:
# Read cluster version
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - watch
  - list
 