apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: accelerator-crb
  namespace: accelerator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: accelerator-clusterrole
subjects:
- kind: ServiceAccount
  name: accelerator-sa
  namespace: accelerator
